image: gradle:6.6.1-jdk14

services:
  - postgres:11.6

variables:
  SERVER_DIR: server
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
  SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD

stages:
  - build
  - test

build_server:
  stage: build
  script: $SERVER_DIR/gradlew -p $SERVER_DIR/ --build-cache assemble
  cache:
    paths:
      - $SERVER_DIR/build
      - $SERVER_DIR/.gradle
  artifacts:
    paths:
      - $SERVER_DIR/build/libs/animal-collector.jar
    expire_in: 1 week
  only:
    - master

test_server:
  stage: test
  variables:
    POSTGRES_DB: ani_co_test
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/$POSTGRES_DB
  script:
    - $SERVER_DIR/gradlew -p $SERVER_DIR/ test
