image: gradle:6.0-jdk11

services:
  - postgres:11.6

variables:
  SERVER_DIR: server

stages:
  - build
  - test

build_server:
  stage: build
  script: $SERVER_DIR/gradlew -p $SERVER_DIR/ --build-cache assemble
  cache:
    paths:
      - $SERVER_DIR/build
      - $SERVER_DIR/.gradle
  artifacts:
    paths:
      - $SERVER_DIR/build/libs/animal-collector.jar
    expire_in: 1 week
    only:
      - master

test_server:
  stage: test
  image: postgres:11.6
  variables:
    POSTGRES_DB: ani_co_test
    POSTGRES_USER: postgres
  script:
    - psql -h postgres -U $POSTGRES_USER -c 'CREATE DATABASE ${POSTGRES_DB} OWNER ${POSTGRES_USER};'
    - $SERVER_DIR/gradlew -p $SERVER_DIR/ test
